### PR TITLE
Update EventWithContext resources to include configuration piece of payload

### PR DESCRIPTION
**Pull request by aaiezza**
SD-7121: Accept other account fields that appear in ADP Subscription Order & User Assignment payloads 

Task-Url: https://ramseysolutions.atlassian.net/browse/SD-7121

### CODE REVIEW

**Comment by spelfrey** [comment]
Are you going to reopen this with the changes proposed to the official repo?

**Comment by aaiezza** [comment]
@spelfrey Yes. Only because it looks like ADP may not be adding the changes any time soon; so we should probably just code review it over here on our end so we can use our fork in the local nexus until they are ready to merge the changes.

**Comment by spelfrey** [comment]
Don't forget to update the pom version here to match what you are using in the provision-api. Helpful for those of us building this locally. 🚔

**Comment by aaiezza** [comment]
This PR was accepted by the AppDirect team! ^_^

**Comment by aaiezza** [comment]
@philipdowner, This PR was successfully merged into the original repo. Do you know the protocol on cleaning this PR up and what to do next? Attempt to keep our fork up to date, delete it entirely, etc.

**Comment by atarpley** [comment]
@philipdowner @aaiezza This PR was never merged into our fork's master branch.
Since this branch was merged into the owner's repo, can we simply close this PR and update our master to match the remote master?

**Comment by philipdowner** [comment]
Closing PR per feedback from @andyman021300 and @aaiezza

**Pull request closed without merging**
